from __future__ import annotations
from typing import Protocol, Iterable

class Storage(Protocol):
    def list_dir(self, path: str) -> tuple[list[str], list[str]]:
        """Return (files, dirs) names in path (no recursion)."""
    def read_bytes(self, path: str) -> bytes:
        ...
    def write_bytes(self, path: str, data: bytes) -> None:
        ...
    def exists(self, path: str) -> bool:
        ...
    def size(self, path: str) -> int:
        ...
    def join(self, *parts: str) -> str:
        ...
    def etag(self, path: str) -> str | None:
        ...
